# Generated by Django 5.0.4 on 2024-05-31 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_letter', models.CharField(max_length=250, verbose_name='Тема письма')),
                ('text_letter', models.TextField(verbose_name='Текст письма')),
                ('img_letter', models.ImageField(blank=True, null=True, upload_to='messages/message', verbose_name='Картинка письма')),
            ],
            options={
                'verbose_name': 'Письмо',
                'verbose_name_plural': 'Письма',
                'db_table': '_ms_messages',
                'db_table_comment': 'Письма',
                'ordering': ['subject_letter'],
                'permissions': [('view_all_messages', 'Can view all Письмо')],
            },
        ),
    ]
