# Generated by Django 5.0.4 on 2024-05-29 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messages_', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messages',
            options={'ordering': ['subject_letter'], 'permissions': [('view_all_messages', 'Can view all Письмо')], 'verbose_name': 'Письмо', 'verbose_name_plural': 'Письма'},
        ),
    ]
