# Generated by Django 5.0.4 on 2024-05-31 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название статьи')),
                ('slug', models.CharField(blank=True, max_length=100, null=True, verbose_name='Slug статьи')),
                ('text', models.TextField(verbose_name='Текст статьи')),
                ('img', models.ImageField(blank=True, default='blog/news/default.jpeg', null=True, upload_to='blog/news/', verbose_name='Превью статьи')),
                ('views', models.IntegerField(default=0, verbose_name='Количество просмотров')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('is_published', models.BooleanField(default=False, verbose_name='Статус публикации')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
                'db_table': '_bl_articles',
                'db_table_comment': 'Статьи',
                'ordering': ['-created_at'],
            },
        ),
    ]
